# Local - run DDL
#   OP=create NETWORK_MODE=host docker compose -f create-load.yml up
#
# Local - load data
#   OP=load NETWORK_MODE=host docker compose -f create-load.yml up
# 
# Swarm - run DDL:
#   OP=create ADDRESS=compute-r0:55432 docker stack deploy --compose-file create-load.yml create
#
# Swarm - load data:
#   OP=load ADDRESS=compute-r0:55432 docker stack deploy --compose-file create-load.yml load
#
version: '3.8'

configs:
  substitute:
    file: ./substitute.sh
  benchmark_config:
    file: ./postgres/${BENCHMARK:-hot}-config.xml
  benchmark_ddl:
    file: ./postgres/${BENCHMARK:-hot}-ddl.sql

networks:
  default:
    name: neon
    external: true

services:
  bb:
    image: ghcr.io/umd-dslam/benchbase-postgres:latest
    configs:
      - source: substitute
        target: /substitute.sh
        mode: 0555 # readable and executable
      - source: benchmark_config
        target: /${BENCHMARK:-hot}-config-template.xml
      - source: benchmark_ddl
        target: /${BENCHMARK:-hot}-ddl.sql
    user: root
    network_mode: ${NETWORK_MODE:-}
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${ADDRESS:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USER=${USER:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - REGION=0
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /benchbase/entrypoint.sh --bench $$BENCHMARK --config /$$BENCHMARK-config.xml --${OP:-create}=true
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.region==0
          - node.labels.has_benchbase==true

