# Neon is run locally
#   export R1="host.docker.internal:55433"
#   export R2="host.docker.internal:55434"
#   export R3="host.docker.internal:55435"
#   NETWORK_MODE=host docker compose -f execute.yml up
# 
# Neon is run with docker compose
#   export R1="compute-r1:55432"
#   export R2="compute-r2:55432"
#   export R3="compute-r3:55432"
#   MINIO=minio:9000 docker compose -f execute.yml up
#
# Neon is run in a swarm
#   export R1="compute-r1:55432"
#   export R2="compute-r2:55432"
#   export R3="compute-r3:55432"
#   MINIO=minio:9000 docker stack deploy --compose-file execute.yml bb
#
version: '3.8'

configs:
  substitute:
    file: ./substitute.sh
  benchmark_config:
    file: ./${DB:-postgres}/${BENCHMARK:-hot}-config.xml
  benchmark_ddl:
    file: ./${DB:-postgres}/${BENCHMARK:-hot}-ddl.sql
  upload-and-clean:
    file: ./upload-and-clean.sh

networks:
  default:
    name: neon
    external: true

services:
  bb-r1: &benchbase
    image: ghcr.io/umd-dslam/benchbase:latest
    configs:
      - source: substitute
        target: /substitute.sh
        mode: 0555 # readable and executable
      - source: benchmark_config
        target: /${BENCHMARK:-hot}-config-template.xml
      - source: benchmark_ddl
        target: /${BENCHMARK:-hot}-ddl.sql
      - source: upload-and-clean
        target: /upload-and-clean.sh
        mode: 0555 # readable and executable
    user: root
    network_mode: ${NETWORK_MODE:-}
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R1:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USER=${USER:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - NUM_REGIONS=3
      - REGION=1
      - MINIO=${MINIO:-}
    entrypoint: 
      - /bin/bash
      - -o
      - pipefail
      - -c
    command:
      - timestamp=$(date +%Y-%m-%d_%H-%M-%S) &&
        /substitute.sh &&
        /benchbase/entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000
          --json-histograms results/histograms.json |
          tee results/log.txt &&
        /upload-and-clean.sh ${TAG:-$$timestamp}/region$$REGION
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.labels.region==1
          - node.labels.has_benchbase==true

  bb-r2:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R2:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USER=${USER:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - NUM_REGIONS=3
      - REGION=2
      - MINIO=${MINIO:-}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.labels.region==2
          - node.labels.has_benchbase==true

  bb-r3:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R3:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USER=${USER:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - NUM_REGIONS=3
      - REGION=3
      - MINIO=${MINIO:-}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints:
          - node.labels.region==3
          - node.labels.has_benchbase==true