# Local
#   export R1="host.docker.internal:55433"
#   export R2="host.docker.internal:55434"
#   export R3="host.docker.internal:55435"
#   NETWORK_MODE=host compose -f execute.yml up
# 
# Swarm
#   export R1="compute-r1:55432"
#   export R2="compute-r2:55432"
#   export R3="compute-r3:55432"
#   MINIO=minio:9000 docker stack deploy --compose-file execute.yaml benchbase
#
version: '3.8'

configs:
  substitute:
    file: ./substitute.sh
  benchmark_config:
    file: ./postgres/${BENCHMARK:-hot}-config.xml
  benchmark_ddl:
    file: ./postgres/${BENCHMARK:-hot}-ddl.sql
  upload:
    file: ./upload.sh

networks:
  default:
    name: neon
    external: true

services:
  benchbase-r1: &benchbase
    image: ghcr.io/umd-dslam/benchbase-postgres:latest
    configs:
      - source: substitute
        target: /substitute.sh
        mode: 0555 # readable and executable
      - source: benchmark_config
        target: /${BENCHMARK:-hot}-config-template.xml
      - source: benchmark_ddl
        target: /${BENCHMARK:-hot}-ddl.sql
      - source: upload
        target: /upload.sh
        mode: 0555 # readable and executable
    user: root
    network_mode: ${NETWORK_MODE:-}
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R1:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - REGION=1
      - MINIO=${MINIO:-localhost:9000}
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region1
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region1
        target: /benchbase/results
    deploy:
      placement:
        constraints:
          - node.labels.region==1
          - node.labels.has_benchbase==true

  benchbase-r2:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R2:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - REGION=2
      - MINIO=${MINIO:-localhost:9000}
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region2
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region2
        target: /benchbase/results
    deploy:
      placement:
        constraints:
          - node.labels.region==2
          - node.labels.has_benchbase==true

  benchbase-r3:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${R3:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD:-}
      - REGION=3
      - MINIO=${MINIO:-localhost:9000}
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region3
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region3
        target: /benchbase/results
    deploy:
      placement:
        constraints:
          - node.labels.has_xactserver==true
          - node.labels.region==0
    deploy:
      placement:
        constraints:
          - node.labels.region==3
          - node.labels.has_benchbase==true