version: '3.8'

configs:
  substitute:
    file: ./substitute.sh
  benchmark_config:
    file: ./postgres/${BENCHMARK:-hot}-config.xml
  benchmark_ddl:
    file: ./postgres/${BENCHMARK:-hot}-ddl.sql
  upload:
    file: ./upload.sh

services:
  benchbase_1: &benchbase
    image: ghcr.io/umd-dslam/benchbase-postgres:latest
    configs:
      - source: substitute
        target: /substitute.sh
      - source: benchmark_config
        target: /${BENCHMARK:-hot}-config-template.xml
      - source: benchmark_ddl
        target: /${BENCHMARK:-hot}-ddl.sql
      - source: upload
        target: /upload.sh
    user: root
    network_mode: host
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${ADDRESS:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=1
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region1
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region1
        target: /benchbase/results

  benchbase_2:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${ADDRESS:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=2
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region2
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region2
        target: /benchbase/results

  benchbase_3:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - ADDRESS=${ADDRESS:-host.docker.internal:55432}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=3
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh
          --bench $$BENCHMARK
          --config /$$BENCHMARK-config.xml
          --execute=true
          --interval-monitor 1000 &&
        /upload.sh ${TAG:-default}/region3
    volumes:
      - type: bind
        source: ./results/${TAG:-default}/region3
        target: /benchbase/results
