version: '3.8'

configs:
  substitute:
    file: ./substitute.sh
  benchmark_config:
    file: ./postgres/${BENCHMARK:-hot}-config.xml
  benchmark_ddl:
    file: ./postgres/${BENCHMARK:-hot}-ddl.sql

services:
  benchbase_1: &benchbase
    image: ghcr.io/umd-dslam/benchbase-postgres:latest
    configs:
      - source: substitute
        target: /substitute.sh
      - source: benchmark_config
        target: /${BENCHMARK:-hot}-config-template.xml
      - source: benchmark_ddl
        target: /${BENCHMARK:-hot}-ddl.sql
    user: root
    network_mode: host
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - HOST=host.docker.internal
      - PORT=55433
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=1
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh --bench $$BENCHMARK --config /$$BENCHMARK-config.xml --execute=true -im 1000
    volumes:
      - type: bind
        source: ./results/region1
        target: /benchbase/results

  benchbase_2:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - HOST=host.docker.internal
      - PORT=55434
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=2
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh --bench $$BENCHMARK --config /$$BENCHMARK-config.xml --execute=true -im 1000
    volumes:
      - type: bind
        source: ./results/region2
        target: /benchbase/results

  benchbase_3:
    <<: *benchbase
    environment:
      - BENCHMARK=${BENCHMARK:-hot}
      - HOST=host.docker.internal
      - PORT={PORT:-55433}
      - DATABASE=${DATABASE:-postgres}
      - USERNAME=${USERNAME:-cloud_admin}
      - PASSWORD=${PASSWORD}
      - REGION=3
    entrypoint: 
      - /bin/bash
      - -c
    command:
      - /substitute.sh && 
        /entrypoint.sh --bench $$BENCHMARK --config /$$BENCHMARK-config.xml --execute=true
    volumes:
      - type: bind
        source: ./results/region3
        target: /benchbase/results
